# Generated by Django 5.0.6 on 2024-06-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culinary_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='culinary_app.ingredients'),
        ),
    ]
